config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  get 'home', to: 'static_pages#home'

  namespace :user do
    root :to => "static_pages#home"
  end

  resources :photos
  resources :users, only: :show
  resources :blogs
  resources :events
  resources :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || home_path
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = current_user.blogs.create(blog_params)
    redirect_to blogs_path
  end

private

  def blog_params
    params.require(:blog).permit(:title, :author, :subtitle, :content)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end


  def create
   @photo = current_user.photos.create(photo_params)
    redirect_to photos_path
  end

  def new
    @photo = Photo.new
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def index

  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/index.html.erb

<body>
  <div class="booyah-box col-12 mt-3">
    <div class="col-12">
        <div class="row feature">
          <div class="col-12 col-lg float-left mb-3">
            <h2>What's the Skinny?</h2>
          </div>

          <div class="col-12 col-sm float-right">
            <div class="float-right mr-3 mt-1">
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#blogModal">
              + Blog Post
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="booyah-box col-12 mt-1">
    <div class="row feature">
      <% @blogs.each do |blog| %>
          <div class="latestPost">
            <div class="col-12 col-lg float-left">
              <div id="content_box">
                  <header>
                    <h3><%= link_to blog.title, blog_path(blog) %></h3>
                  </header><br />

                  <hr>
                  <i><%= blog.subtitle %></i><br />
                  <br />

                  <div class="row">
                    <div class="col-6">
                        <p>Posted by: <%= blog.author %></p>
                    </div>
                      </br>
                    <div class="col-6 float-right">
                      <p><%= l blog.created_at.to_date, format: :long %></p>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        <% end %>

    </div>
  </div>

</body>

<!-- Blog Modal -->
<div class="modal fade" id="blogModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Tell Us What's Up</h4>
      </div>

      <%= simple_form_for(Blog.new, :url => { :action => "create" }) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :content %>
          <%= f.input :author %>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Post", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.hmtl.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new blog</h1>
</div>

app/views/blogs/new.html.erb
<div class="booyah-box col-8 offset-2  mt-5">
  <h1>Post a Blog</h1>
  <%= simple_form_for @blog do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :content %>
    <%= f.input :author %>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
 </div>

app/views/blogs/show.html.erb
<br />

<div class="booyah-box col-12">

  <h2><%= @blog.title %></h2>

  <br />
  <div class="row mb-2">
    <div class="col-sm-8 col-12 ml-5">
      <%= @blog.subtitle %>
    </div>
    <div class="col-sm-8 col-12 ml-5">
      <%= @blog.author %>
    </div>
  </div>
  <hr>

  <div class="row ml-5">
    <%= @blog.content %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gurltalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="col-10 offset-1">

    <nav class="navbar navbar-expand-lg navbar-inverse bg-inverse">
      <% if current_user %>
          <%= link_to 'GurlTalk', home_url, class: 'navbar-brand' %>
        <% else %>
         <%= link_to 'GurlTalk', root_url, class: 'navbar-brand' %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">



        <ul class="navbar-nav mr-auto">
          <% if current_user %>

            <li class="nav-item active">
              <%= link_to 'Home', home_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">
              <%= link_to 'Photos', photos_path, class: 'nav-link' %>
            </li>

          <li class="nav-item">
            <%= link_to 'Blogs', blogs_path, class: 'nav-link' %>
        </li>

            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>


          <% else %>

            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>

      <div id="search-box">
        <script async src="https://cse.google.com/cse.js?cx=001206432501022560131:7lnc4tr8sr7"></script>
        <div class="gcse-search"></div>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/photos/index.html.erb

<div class="float-right mr-5 mt-1">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#photoModal">
    + Photo
  </button>
</div>

 <div class="row text-center text-lg-left mt-5">
  <div class="col-lg-3 col-md-4 col-6"></div>
    <div class="container" id="photos">
      <% @photos.each do |photo| %>
        <%= image_tag photo.image.to_s, class: 'img-fluid' %>
      <% end %>
    </div>
  </div>
</div>

<!-- Photo Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Share a Photo</h4>
      </div>

      <%= simple_form_for(Photo.new, :url => { :action => "create" }) do |f| %>
        <div class="modal-body">
          <%= f.input :image %>
          <%= f.input :caption %>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Post", class: 'btn btn-primary' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="booyah-box col-8 offset-2  mt-5">
  <h1>Share a Photo</h1>
  <%= simple_form_for @photo do |f| %>
    <%= f.input :image %>
    <%= f.input :caption %>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
 </div>

app/views/static_pages/home.html.erb
<html>
  <head>
    <script src="https://kit.fontawesome.com/7e4875713f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="booyah-box col-12 mt-3">
    <div class="col-8 offset-2 mt-3">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <%= image_tag 'slider1.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <h3>Duck Face</h3>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag 'slider2.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <h3>The whole fam!</h3>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag 'slider3.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <h3>Mi Bruhas. Love.</h3>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>


    <br />
    <div class="row feature text-center mt-3">
        <div class="col-12 col-sm">
          <%= link_to new_photo_path do  %>
          <i class="fas fa-camera-retro fa-5x mb-3" style="color:teal" ></i>
          <% end %>
          <br />
          <p>Share your beautiful faces, ladies!</p>
        </div>

        <div class="col-12 col-sm">
          <%= link_to "#" do  %>
          <i class="far fa-calendar-alt fa-5x mb-3" style="color:purple" ></i>
          <% end %>
          <br />
          <p>Let's Hang Out!</p>
        </div>

        <div class="col-12 col-sm">
          <%= link_to new_blog_path do  %>
          <i class="fas fa-edit fa-5x mb-3" style="color:#1DCD2B" ></i>
        <% end %>
        <br />
          <p>Spill the T, gurl!</p>
        </div>
    </div>
  </div>


  </body>
</html>

app/views/static_pages/index.html.erb
</br>
<h1 class="text-center">Only for Karen, Gina & Tiffany. Keep Out!</h1>

<div class="booyah-box col-8 offset-2">
  <h2>Welcome PYTs!</h2>

  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="row">
    <div class="col-12 col-sm-8">
     <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-12 col-sm-8">
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>
    </div>
  </div>

</br>
      <% if devise_mapping.rememberable? %>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end %>

      <div class="row">
        <div class="col-12 col-sm-8">
      <div class="actions">
        <%= f.submit "Log in" %>

      </div>
    </div>
  </div>
    <% end %>

</div>